package com.labresource.platform.notification;

public enum NotificationEventType {
    BOOKING_PENDING,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_NO_SHOW,
    WAITLIST_AVAILABLE,
    MAINTENANCE_SCHEDULED,
    WORK_ORDER_ASSIGNED,
    CALIBRATION_EXPIRING_SOON,
    CALIBRATION_EXPIRED,
    CERTIFICATION_EXPIRING_SOON,
    CERTIFICATION_EXPIRED,
    SHARING_REQUEST_RECEIVED,
    SHARING_REQUEST_APPROVED,
    IDLE_ALERT,
    INVOICE_GENERATED
}
